language: python
python: 
    - "3.6"
script: python pydmrg/tests.py 
branches:
   only:
       - master
notifications:
    email: false
os:
    - linux
install:
    - pip install matplotlib
    - pip install pyscf
